### ISSUE TITLE
I want to get snapshot

### ISSUE THREAD

**Issue by masa8** [ageof/MyDlink-API-Python#1]
Hi, 

Thank you for your great code.
This is nice but I wanted to get snapshot.

So I tried to post https://mp-eu-openapi.auto.mydlink.com/v2/device/live/snapshot?access_token=<TOKEN\>  with this kind payload {data: {mydlink_id: "<MYDLINKID\>", uid: 0, idx: 0, size: 2}} but What I got was 400 Error says "Client doesnt have privilege."

Do you know the way to get snapshot? if you know that, Can you add this function?
I'm thinking there is no way to do that. I guess..

Anyway, thank you for your code. I learned a lot :-)

**Comment by ageof** [comment]
Hi,
thanks for your feedback.
Live view and live snapshot is complicated in the old app version this was only possible via an SSO connection. The only thing that is almost completely implemented is the downloading of the cloud recordings.

**Comment by masa8** [comment]
Thank you for your reply.
I understand that.
Your reply was a big help
Thank you🙂
