### ISSUE TITLE
Latest version of app seems to break.

### ISSUE THREAD

**Issue by bremor** [ageof/MyDlink-API-Python#2]
I have been doing a bit of testing and I'm thinking the "oauth_secret" has changed, or the method for calculating a signature has changed.

**Comment by bremor** [comment]
How did you get the oauth secret and sig method originally? Did you have to decompile the app?

**Comment by ageof** [comment]
One Way is to decompile the apk file. You can Download the APK [from her](https://apkpure.com/de/mydlink/com.dlink.mydlinkunified).  
To decompile, just [use this page](http://www.javadecompilers.com/apk), it is the easiest way.
The Second way is to use CharlsProxy and Sniff the traffic between MydlinkApp and the Server.

**Comment by ageof** [comment]
If you update your project the login goes again. I just put in a fix. They added new header fields to the request and checked them
